In [1]:

"""
2. Lending Club loan default predictor

Loan default occurs when a borrower fails to pay back a debt according
to the initial arrangement. In the case of most consumer loans, this means
that successive payments have been missed over the course of weeks or months. 
Fortunately, lenders and loan servicer usually allow a grace period before penalizing 
the borrower after missing one payment. The period between missing a loan payment 
and having the loan default is known as delinquency. The delinquency period gives 
the debtor time to avoid default by contacting their loan servicer or making up 
missed payments.

Defaulting on a loan will cause a substantial and lasting drop in the debtor's credit 
score, as well as extremely high interest rates on any future loan. For loans 
ecured with collateral, defaulting will likely result in the pledged asset being 
seized by the bank. The most popular types of consumer loans that are backed by collateral 
are mortgages, auto loans and secured personal loans. For unsecured debts like credit cards 
and student loans, the consequences of default vary in severity according to the type
of loan. In the most extreme cases, debt collection agencies can garnish wages to
pay back the outstanding debt. The loan is one of the most important products of the banking. 
All the banks are trying to figure out effective business strategies to persuade customers 
to apply their loans. However, there are some customers behave negatively after their 
application are approved.

linkcode
Data link:(~400MB file. Practice Patience)
https://drive.google.com/file/d/1e5gfIjJGJ7o7u27sW8c8gLRm8qmd0HJt/view?usp=sharing
Reference: Lending_club_loan_default_predictor | Kaggle

Follow these steps and create Credit Default Predictor ML model
● Problem Statement Analysis 
The objective is to use the loan data to build a model that can predict the loan status
(whether or not a loan will be fully paid or charged off) and interpret the results to find 
the factors, which affect the result. We want to develop a model that is accurate and interpretable.

● Reading Dataset and First look 
In this project, I will work with the publicly available Lending Club data 
on Kaggle https://drive.google.com/file/d/1e5gfIjJGJ7o7u27sW8c8gLRm8qmd0HJt/view?usp=sharing
Reference: Lending_club_loan_default_predictor | Kaggle
● Column Information

● looking for More information

● Exploratory Data Analysis (EDA)

● Numerical Features Analysis

● Categorical Data Analysis 
The dataset has numerical, /*categorical and missing values. 
Because there are so many features (150+), i will start the data 
engineering with dropping unnecessary features and then deal with 
the remaining features more in detail.

● Data PreProcessing

● Making The Base Line Model 
As features are measured in different units, they cover different ranges. 
The range of the features therefore significantly affects some ML models, 
such as SVM, KNN that take into account distance measures between observations 
and scaling allows them to learn. While some methods, such as Linear Regression and 
Ransom Forest do not actually require feature scaling, it's still best practice to 
take this step when we are comparing multiple algorithms.

● Support Vector Machine
● Baseline models
● Choosing the models
● XG Boost Classifier
● Conclusion
● Recommendation
"""

"\n2. Lending Club loan default predictor\n\nLoan default occurs when a borrower fails to pay back a debt according\nto the initial arrangement. In the case of most consumer loans, this means\nthat successive payments have been missed over the course of weeks or months. \nFortunately, lenders and loan servicer usually allow a grace period before penalizing \nthe borrower after missing one payment. The period between missing a loan payment \nand having the loan default is known as delinquency. The delinquency period gives \nthe debtor time to avoid default by contacting their loan servicer or making up \nmissed payments.\n\nDefaulting on a loan will cause a substantial and lasting drop in the debtor's credit \nscore, as well as extremely high interest rates on any future loan. For loans \necured with collateral, defaulting will likely result in the pledged asset being \nseized by the bank. The most popular types of consumer loans that are backed by collateral \nare mortgages, auto loans and secured personal loans. For unsecured debts like credit cards \nand student loans, the consequences of default vary in severity according to the type\nof loan. In the most extreme cases, debt collection agencies can garnish wages to\npay back the outstanding debt. The loan is one of the most important products of the banking. \nAll the banks are trying to figure out effective business strategies to persuade customers \nto apply their loans. However, there are some customers behave negatively after their \napplication are approved.\n\nlinkcode\nData link:(~400MB file. Practice Patience)\nhttps://drive.google.com/file/d/1e5gfIjJGJ7o7u27sW8c8gLRm8qmd0HJt/view?usp=sharing\nReference: Lending_club_loan_default_predictor | Kaggle\n\nFollow these steps and create Credit Default Predictor ML model\n● Problem Statement Analysis \nThe objective is to use the loan data to build a model that can predict the loan status\n(whether or not a loan will be fully paid or charged off) and interpret the results to find \nthe factors, which affect the result. We want to develop a model that is accurate and interpretable.\n\n● Reading Dataset and First look \nIn this project, I will work with the publicly available Lending Club data \non Kaggle https://drive.google.com/file/d/1e5gfIjJGJ7o7u27sW8c8gLRm8qmd0HJt/view?usp=sharing\nReference: Lending_club_loan_default_predictor | Kaggle\n● Column Information\n\n● looking for More information\n\n● Exploratory Data Analysis (EDA)\n\n● Numerical Features Analysis\n\n● Categorical Data Analysis \nThe dataset has numerical, /*categorical and missing values. \nBecause there are so many features (150+), i will start the data \nengineering with dropping unnecessary features and then deal with \nthe remaining features more in detail.\n\n● Data PreProcessing\n\n● Making The Base Line Model \nAs features are measured in different units, they cover different ranges. \nThe range of the features therefore significantly affects some ML models, \nsuch as SVM, KNN that take into account distance measures between observations \nand scaling allows them to learn. While some methods, such as Linear Regression and \nRansom Forest do not actually require feature scaling, it's still best practice to \ntake this step when we are comparing multiple algorithms.\n\n● Support Vector Machine\n● Baseline models\n● Choosing the models\n● XG Boost Classifier\n● Conclusion\n● Recommendation\n"

In [18]:
# Imports
# Import necessary libraries
!pip install rawdata
import os
import re
import pandas as pd
from pandas import Series, DataFrame
import pandas_profiling
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import itertools
import gzip
import chardet
import io
from IPython.display import display_html
from collections import Counter
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC, LinearSVC
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier,ExtraTreesClassifier, VotingClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV, cross_val_score, StratifiedKFold, learning_curve, cross_validate
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, make_scorer
from sklearn import metrics
from copy import copy
from functools import partial
from collections.abc import Iterable, Sequence, Mapping
from numbers import Number
from datetime import datetime
from distutils.version import LooseVersion
from numpy.core import numerictypes

from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score
import time
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
%matplotlib inline

# ignore Deprecation Warning
sns.set_style('whitegrid')
%matplotlib inline

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: rawdata in /usr/local/lib/python3.8/dist-packages (0.1.0)
Requirement already satisfied: nose>=1.0 in /usr/local/lib/python3.8/dist-packages (from rawdata) (1.3.7)

In [19]:
from pandas.io.formats.info import DataFrameInfo

# Load the data into a dataframe
df = pd.read_csv("loan.csv",nrows=5)
print(df.sample(5))
print(df.info(5)) 

#Looking for more information 

print('Loan Status:')
df['loan_status'].value_counts()
print('Term:')
print(df['term'].value_counts(dropna=False))
print('Loan Amount:')
print(df['loan_amnt'].value_counts())
print('State')
print(df['addr_state'].describe())
print('Title:')
print(df['title'].value_counts().head(10))
df.sample(5)

        id  member_id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
4  1075358    1311748       3000         3000             3000   60 months
3  1076863    1277178      10000        10000            10000   36 months
0  1077501    1296599       5000         5000             4975   36 months
2  1077175    1313524       2400         2400             2400   36 months
1  1077430    1314167       2500         2500             2500   60 months

  int_rate  installment grade sub_grade  ... num_tl_90g_dpd_24m  \
4   12.69%        67.79     B        B5  ...                NaN
3   13.49%       339.31     C        C1  ...                NaN
0   10.65%       162.87     B        B2  ...                NaN
2   15.96%        84.33     C        C5  ...                NaN
1   15.27%        59.83     C        C4  ...                NaN

  num_tl_op_past_12m pct_tl_nvr_dlq  percent_bc_gt_75 pub_rec_bankruptcies  \
4                NaN            NaN               NaN                    0
3                NaN            NaN               NaN                    0
0                NaN            NaN               NaN                    0
2                NaN            NaN               NaN                    0
1                NaN            NaN               NaN                    0

  tax_liens tot_hi_cred_lim total_bal_ex_mort total_bc_limit  \
4         0             NaN               NaN            NaN
3         0             NaN               NaN            NaN
0         0             NaN               NaN            NaN
2         0             NaN               NaN            NaN
1         0             NaN               NaN            NaN

  total_il_high_credit_limit
4                        NaN
3                        NaN
0                        NaN
2                        NaN
1                        NaN

[5 rows x 111 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 111 columns):
 #    Column                          Dtype
---   ------                          -----
 0    id                              int64
 1    member_id                       int64
 2    loan_amnt                       int64
 3    funded_amnt                     int64
 4    funded_amnt_inv                 int64
 5    term                            object
 6    int_rate                        object
 7    installment                     float64
 8    grade                           object
 9    sub_grade                       object
 10   emp_title                       object
 11   emp_length                      object
 12   home_ownership                  object
 13   annual_inc                      int64
 14   verification_status             object
 15   issue_d                         object
 16   loan_status                     object
 17   pymnt_plan                      object
 18   url                             object
 19   desc                            object
 20   purpose                         object
 21   title                           object
 22   zip_code                        object
 23   addr_state                      object
 24   dti                             float64
 25   delinq_2yrs                     int64
 26   earliest_cr_line                object
 27   inq_last_6mths                  int64
 28   mths_since_last_delinq          float64
 29   mths_since_last_record          float64
 30   open_acc                        int64
 31   pub_rec                         int64
 32   revol_bal                       int64
 33   revol_util                      object
 34   total_acc                       int64
 35   initial_list_status             object
 36   out_prncp                       float64
 37   out_prncp_inv                   float64
 38   total_pymnt                     float64
 39   total_pymnt_inv                 float64
 40   total_rec_prncp                 float64
 41   total_rec_int                   float64
 42   total_rec_late_fee              float64
 43   recoveries                      float64
 44   collection_recovery_fee         float64
 45   last_pymnt_d                    object
 46   last_pymnt_amnt                 float64
 47   next_pymnt_d                    object
 48   last_credit_pull_d              object
 49   collections_12_mths_ex_med      int64
 50   mths_since_last_major_derog     float64
 51   policy_code                     int64
 52   application_type                object
 53   annual_inc_joint                float64
 54   dti_joint                       float64
 55   verification_status_joint       float64
 56   acc_now_delinq                  int64
 57   tot_coll_amt                    float64
 58   tot_cur_bal                     float64
 59   open_acc_6m                     float64
 60   open_il_6m                      float64
 61   open_il_12m                     float64
 62   open_il_24m                     float64
 63   mths_since_rcnt_il              float64
 64   total_bal_il                    float64
 65   il_util                         float64
 66   open_rv_12m                     float64
 67   open_rv_24m                     float64
 68   max_bal_bc                      float64
 69   all_util                        float64
 70   total_rev_hi_lim                float64
 71   inq_fi                          float64
 72   total_cu_tl                     float64
 73   inq_last_12m                    float64
 74   acc_open_past_24mths            float64
 75   avg_cur_bal                     float64
 76   bc_open_to_buy                  float64
 77   bc_util                         float64
 78   chargeoff_within_12_mths        int64
 79   delinq_amnt                     int64
 80   mo_sin_old_il_acct              float64
 81   mo_sin_old_rev_tl_op            float64
 82   mo_sin_rcnt_rev_tl_op           float64
 83   mo_sin_rcnt_tl                  float64
 84   mort_acc                        float64
 85   mths_since_recent_bc            float64
 86   mths_since_recent_bc_dlq        float64
 87   mths_since_recent_inq           float64
 88   mths_since_recent_revol_delinq  float64
 89   num_accts_ever_120_pd           float64
 90   num_actv_bc_tl                  float64
 91   num_actv_rev_tl                 float64
 92   num_bc_sats                     float64
 93   num_bc_tl                       float64
 94   num_il_tl                       float64
 95   num_op_rev_tl                   float64
 96   num_rev_accts                   float64
 97   num_rev_tl_bal_gt_0             float64
 98   num_sats                        float64
 99   num_tl_120dpd_2m                float64
 100  num_tl_30dpd                    float64
 101  num_tl_90g_dpd_24m              float64
 102  num_tl_op_past_12m              float64
 103  pct_tl_nvr_dlq                  float64
 104  percent_bc_gt_75                float64
 105  pub_rec_bankruptcies            int64
 106  tax_liens                       int64
 107  tot_hi_cred_lim                 float64
 108  total_bal_ex_mort               float64
 109  total_bc_limit                  float64
 110  total_il_high_credit_limit      float64
dtypes: float64(68), int64(19), object(24)
memory usage: 4.5+ KB
None
Loan Status:
Term:
 36 months    3
 60 months    2
Name: term, dtype: int64
Loan Amount:
5000     1
2500     1
2400     1
10000    1
3000     1
Name: loan_amnt, dtype: int64
State
count      5
unique     5
top       AZ
freq       1
Name: addr_state, dtype: object
Title:
Computer                1
bike                    1
real estate business    1
personel                1
Personal                1
Name: title, dtype: int64

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,1077501,1296599,5000,5000,4975,36 months,10.65%,162.87,B,B2,...,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN
4,1075358,1311748,3000,3000,3000,60 months,12.69%,67.79,B,B5,...,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN
1,1077430,1314167,2500,2500,2500,60 months,15.27%,59.83,C,C4,...,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN
2,1077175,1313524,2400,2400,2400,36 months,15.96%,84.33,C,C5,...,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN
3,1076863,1277178,10000,10000,10000,36 months,13.49%,339.31,C,C1,...,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN

In [20]:
# ● Exploratory Data Analysis (EDA)
#Define a function to visulize the features with missing values, and % of total values, & datatype
def missing_values_table(df):
     # Total missing values
    mis_val = df.isnull().sum()
    # Percentage of missing values
    mis_val_percent = 100 * df.isnull().sum() / len(df)
    mis_val_type = df.dtypes
    # Make a table with the results
    mis_val_table = pd.concat([mis_val, mis_val_percent, mis_val_type], axis=1)
        
     # Rename the columns
    mis_val_table_ren_columns = mis_val_table.rename(columns = {0 : 'Missing Values', 1 : '% of Total Values', 2: 'type'})
        
    # Sort the table by percentage of missing descending
    mis_val_table_ren_columns = mis_val_table_ren_columns[ mis_val_table_ren_columns.iloc[:,1] != 0].sort_values('% of Total Values', ascending=False).round(1)
        
    # Print some summary information
    print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n" "There are " + str(mis_val_table_ren_columns.shape[0]) + " columns that have missing values.")
        
    # Return the dataframe with missing information
    return mis_val_table_ren_columns

In [21]:
print(sorted(df.columns))# sort columns 
#print(len(drop_list))
print(len(df.columns))
print(df['id'].sample)
print(df.describe)
df['term'].sample(5)

missing_values_table(df)

['acc_now_delinq', 'acc_open_past_24mths', 'addr_state', 'all_util', 'annual_inc', 'annual_inc_joint', 'application_type', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util', 'chargeoff_within_12_mths', 'collection_recovery_fee', 'collections_12_mths_ex_med', 'delinq_2yrs', 'delinq_amnt', 'desc', 'dti', 'dti_joint', 'earliest_cr_line', 'emp_length', 'emp_title', 'funded_amnt', 'funded_amnt_inv', 'grade', 'home_ownership', 'id', 'il_util', 'initial_list_status', 'inq_fi', 'inq_last_12m', 'inq_last_6mths', 'installment', 'int_rate', 'issue_d', 'last_credit_pull_d', 'last_pymnt_amnt', 'last_pymnt_d', 'loan_amnt', 'loan_status', 'max_bal_bc', 'member_id', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_last_delinq', 'mths_since_last_major_derog', 'mths_since_last_record', 'mths_since_rcnt_il', 'mths_since_recent_bc', 'mths_since_recent_bc_dlq', 'mths_since_recent_inq', 'mths_since_recent_revol_delinq', 'next_pymnt_d', 'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'open_acc', 'open_acc_6m', 'open_il_12m', 'open_il_24m', 'open_il_6m', 'open_rv_12m', 'open_rv_24m', 'out_prncp', 'out_prncp_inv', 'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'policy_code', 'pub_rec', 'pub_rec_bankruptcies', 'purpose', 'pymnt_plan', 'recoveries', 'revol_bal', 'revol_util', 'sub_grade', 'tax_liens', 'term', 'title', 'tot_coll_amt', 'tot_cur_bal', 'tot_hi_cred_lim', 'total_acc', 'total_bal_ex_mort', 'total_bal_il', 'total_bc_limit', 'total_cu_tl', 'total_il_high_credit_limit', 'total_pymnt', 'total_pymnt_inv', 'total_rec_int', 'total_rec_late_fee', 'total_rec_prncp', 'total_rev_hi_lim', 'url', 'verification_status', 'verification_status_joint', 'zip_code']
111
<bound method NDFrame.sample of 0    1077501
1    1077430
2    1077175
3    1076863
4    1075358
Name: id, dtype: int64>
<bound method NDFrame.describe of         id  member_id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
0  1077501    1296599       5000         5000             4975   36 months
1  1077430    1314167       2500         2500             2500   60 months
2  1077175    1313524       2400         2400             2400   36 months
3  1076863    1277178      10000        10000            10000   36 months
4  1075358    1311748       3000         3000             3000   60 months

  int_rate  installment grade sub_grade  ... num_tl_90g_dpd_24m  \
0   10.65%       162.87     B        B2  ...                NaN
1   15.27%        59.83     C        C4  ...                NaN
2   15.96%        84.33     C        C5  ...                NaN
3   13.49%       339.31     C        C1  ...                NaN
4   12.69%        67.79     B        B5  ...                NaN

  num_tl_op_past_12m pct_tl_nvr_dlq  percent_bc_gt_75 pub_rec_bankruptcies  \
0                NaN            NaN               NaN                    0
1                NaN            NaN               NaN                    0
2                NaN            NaN               NaN                    0
3                NaN            NaN               NaN                    0
4                NaN            NaN               NaN                    0

  tax_liens tot_hi_cred_lim total_bal_ex_mort total_bc_limit  \
0         0             NaN               NaN            NaN
1         0             NaN               NaN            NaN
2         0             NaN               NaN            NaN
3         0             NaN               NaN            NaN
4         0             NaN               NaN            NaN

  total_il_high_credit_limit
0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN

[5 rows x 111 columns]>
Your selected dataframe has 111 columns.
There are 59 columns that have missing values.

                                Missing Values  % of Total Values     type
bc_util                                      5              100.0  float64
num_il_tl                                    5              100.0  float64
mo_sin_rcnt_rev_tl_op                        5              100.0  float64
mo_sin_rcnt_tl                               5              100.0  float64
mort_acc                                     5              100.0  float64
mths_since_recent_bc                         5              100.0  float64
mths_since_recent_bc_dlq                     5              100.0  float64
mths_since_recent_inq                        5              100.0  float64
mths_since_recent_revol_delinq               5              100.0  float64
num_accts_ever_120_pd                        5              100.0  float64
num_actv_bc_tl                               5              100.0  float64
num_actv_rev_tl                              5              100.0  float64
num_bc_sats                                  5              100.0  float64
num_bc_tl                                    5              100.0  float64
num_op_rev_tl                                5              100.0  float64
mo_sin_old_il_acct                           5              100.0  float64
num_rev_accts                                5              100.0  float64
num_rev_tl_bal_gt_0                          5              100.0  float64
num_sats                                     5              100.0  float64
num_tl_120dpd_2m                             5              100.0  float64
num_tl_30dpd                                 5              100.0  float64
num_tl_90g_dpd_24m                           5              100.0  float64
num_tl_op_past_12m                           5              100.0  float64
pct_tl_nvr_dlq                               5              100.0  float64
percent_bc_gt_75                             5              100.0  float64
tot_hi_cred_lim                              5              100.0  float64
total_bal_ex_mort                            5              100.0  float64
total_bc_limit                               5              100.0  float64
mo_sin_old_rev_tl_op                         5              100.0  float64
total_il_high_credit_limit                   5              100.0  float64
mths_since_rcnt_il                           5              100.0  float64
bc_open_to_buy                               5              100.0  float64
mths_since_last_major_derog                  5              100.0  float64
annual_inc_joint                             5              100.0  float64
dti_joint                                    5              100.0  float64
verification_status_joint                    5              100.0  float64
tot_coll_amt                                 5              100.0  float64
tot_cur_bal                                  5              100.0  float64
open_acc_6m                                  5              100.0  float64
open_il_6m                                   5              100.0  float64
open_il_12m                                  5              100.0  float64
open_il_24m                                  5              100.0  float64
total_bal_il                                 5              100.0  float64
il_util                                      5              100.0  float64
open_rv_12m                                  5              100.0  float64
open_rv_24m                                  5              100.0  float64
max_bal_bc                                   5              100.0  float64
all_util                                     5              100.0  float64
total_rev_hi_lim                             5              100.0  float64
inq_fi                                       5              100.0  float64
total_cu_tl                                  5              100.0  float64
inq_last_12m                                 5              100.0  float64
acc_open_past_24mths                         5              100.0  float64
avg_cur_bal                                  5              100.0  float64
mths_since_last_record                       5              100.0  float64
next_pymnt_d                                 4               80.0   object
mths_since_last_delinq                       3               60.0  float64
emp_title                                    2               40.0   object
desc                                         1               20.0   object

In [22]:
# make general plots to examine each feature
def plot_var(col_name, full_name, continuous):
    """
    Visualize a variable with/without faceting on the loan status.
    - col_name is the variable name in the dataframe
    - full_name is the full variable name
    - continuous is True for continuous variables
    """
    fig, (ax1, ax2) = plt.subplots(1, 2, sharex=False, figsize=(15,3))
    # plot1: counts distribution of the variable
    
    if continuous:  
        sns.distplot(df.loc[df[col_name].notnull(), col_name], kde=False, ax=ax1)
    else:
        sns.countplot(df[col_name], order=sorted(df[col_name].unique()), color='#5975A4', saturation=1, ax=ax1)
    ax1.set_xlabel(full_name)
    ax1.set_ylabel('Count')
    ax1.set_title(full_name)

          
    # plot2: bar plot of the variable grouped by loan_status
    if continuous:
        sns.boxplot(x=col_name, y='loan_status', data=df, ax=ax2)
        ax2.set_ylabel('')
        ax2.set_title(full_name + ' by Loan Status')
    else:
        Charged_Off_rates = df.groupby(col_name)['loan_status'].value_counts(normalize=True)[:,'Charged Off']
        sns.barplot(x=Charged_Off_rates.index, y=Charged_Off_rates.values, color='#5975A4', saturation=1, ax=ax2)
        ax2.set_ylabel('Fraction of Loans Charged Off')
        ax2.set_title('Charged Off Rate by ' + full_name)
        ax2.set_xlabel(full_name)
    
    # plot3: kde plot of the variable gropued by loan_status
    if continuous:  
        facet = sns.FacetGrid(df, hue = 'loan_status', size=3, aspect=4)
        facet.map(sns.kdeplot, col_name, shade=True)
        #facet.set(xlim=(df[col_name].min(), df[col_name].max()))
        facet.add_legend()  
    else:
        fig = plt.figure(figsize=(12,3))
        sns.countplot(x=col_name, hue='loan_status', data=df, order=sorted(df[col_name].unique()) )
     
    plt.tight_layout()

In [8]:
#Feature Selection II: (Linear) correlation between (numerical) features
#5.1 Convert target variable to 0/1 indicator

def create_target(df):
    """
    Creates target variable by converting loan_status to 0/1 indicator
    """
    df['target'] = np.where(df['loan_status'] == 'Charged Off', 1, 0)
    df.drop('loan_status', axis=1, inplace=True)
    return df

In [23]:
#5.2 K-S test


def ks_test(df, col, target):
    """
    Performs the Kolmogorov-Smirnov test on a numerical feature
    """
    ks = stats.ks_2samp(df[df[target]==0][col], df[df[target]==1][col])
    return ks

In [24]:
#5.3 Pearson Correlation

def corr_features(df, target, threshold):
    """
    Returns features with a Pearson correlation over the threshold
    """
    corr = df.corr()[target].sort_values(ascending=False)
    corr_feats = corr[abs(corr) > threshold].index.tolist()
    return corr_feats#

In [25]:
#6.1 Dummy variables


def create_dummies(df, cat_cols):
    """
    Creates dummy variables for categorical features
    """
    for col in cat_cols:
        dummies = pd.get_dummies(df[col], prefix=col, drop_first=True)
        df = pd.concat([df, dummies], axis=1)
    df.drop(cat_cols, axis=1, inplace=True)
    return df